export const CHANGE_INPUT = 'CHANGE_INPUT'
export const ADD_ITEMS = 'ADD_ITEMS'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const GET_LIST_ITEM = 'GET_LIST_ITEM'
export const GET_MY_LIST = 'GET_MY_LIST'